### PR TITLE
HI - hope you dont mind but i kinda re-wrote some of you site to use better html pracsices and so on

### PR DESCRIPTION
**Pull request by Shinigami072**

### CODE REVIEW

**Comment by ignitefitness** [comment]
I'm definately fine with you reworking my code. I should have mentioned that this site is only really designed to be viewed on a phone, hence my use of table tag instead of div tag and lack of responsive web design. I am still struggling though with how images are being handled on github. When I download the folder and load the project in Brackets all of my images load fine, but for all of the pages outside of index.html no images will load in Github. Could you please explain what changes I need to make?

**Review by ignitefitness — APPROVED** [review]

**Comment by Shinigami072** [comment]
I resolved some conflicts - with these changes the images will load,
I also made sure the responsive design i used would behave properly on a mobile device

The problem with the images is the same as the one with links

The images you included all have url of "/images/*.{jpeg|gif}" - a url beginning with a '/' is called an absolute url - because it always points to the same file.

This is true when the root of the document is the same as root of the web page you see github hosts your files on your domain `$username.github.io` but each project has its own "directory" on that domain `$username.github.io/$reponame` -> this is fine and good because it allows you to host multiple sites on github. 

An "unexpected" consequence is however that your document's "root" and your website's "root" are different -> '/' resolves to `$username.github.io/` instead of `$username.github.io/$reponame`.

A solution is to use relative urls instead of absolute ones. That way you can move the whole document wherever and it will still link itself properly. (a disadvantage is that you have to change the url if you move the file relatively to each other)

'..' means parent directory.
so if you have a file structure like this

```
dir1/file1
dir1/dir3/file3
dir1/dir2/file2
dir2/file2
```
relative path from file1 `../folder2/file2` would resolve to  `/dir2/file2`
however from file 3 it would resolve to `/dir1/dir2/file2`

**Comment by Shinigami072** [comment]
In terms of things you should still do to improve your site i would say image compression is pretty high on the list especially if you target a mobile target - > the images you have used are pretty high quality which is great - however this means they will take a long time to download -> which is not ideal especially if they are going to be relatively small - all things considered 

Another thing is gifs - they are not the greatest format for moving images for multiple reasons. (bad compression, poor streaming capabilities fe.)
I would consider using `.webm`. which would be more suitable and  would have the added benefit of having playback controls if necessary. 

In an ideal scenario you would have multiple sources of images -> and depending on the browsers resolution using different ones, but honestly i have no idea how to achieve this sort of thing since I'm not a front-end developer at all

**Comment by ignitefitness** [comment]
-

**Comment by ignitefitness** [comment]
This pull request is showing up for me as closed, How do I reopen it so I can merge the whole request?

**Pull request merged**
